{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 82,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Milliseconds</th>\n",
       "      <th>timezoneOffset</th>\n",
       "      <th>timestamp</th>\n",
       "      <th>DayOfYear</th>\n",
       "      <th>DayOfMonth</th>\n",
       "      <th>DayOfWeek</th>\n",
       "      <th>TimeOfDay</th>\n",
       "      <th>_id</th>\n",
       "      <th>cat1</th>\n",
       "      <th>cat2</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1230751126776</td>\n",
       "      <td>3600000</td>\n",
       "      <td>2008-12-31T20:18:46.776+01:00</td>\n",
       "      <td>366</td>\n",
       "      <td>31</td>\n",
       "      <td>Wednesday</td>\n",
       "      <td>20.312778</td>\n",
       "      <td>2903</td>\n",
       "      <td>Toltesek</td>\n",
       "      <td>PSVita</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1526304739951</td>\n",
       "      <td>7200000</td>\n",
       "      <td>2018-05-14T15:32:19.951+02:00</td>\n",
       "      <td>134</td>\n",
       "      <td>14</td>\n",
       "      <td>Monday</td>\n",
       "      <td>15.538611</td>\n",
       "      <td>10</td>\n",
       "      <td>Erkezes/Indulas</td>\n",
       "      <td>Dési Out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1526306116707</td>\n",
       "      <td>7200000</td>\n",
       "      <td>2018-05-14T15:55:16.707+02:00</td>\n",
       "      <td>134</td>\n",
       "      <td>14</td>\n",
       "      <td>Monday</td>\n",
       "      <td>15.921111</td>\n",
       "      <td>11</td>\n",
       "      <td>Erkezes/Indulas</td>\n",
       "      <td>Dési In</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1526318780295</td>\n",
       "      <td>7200000</td>\n",
       "      <td>2018-05-14T19:26:20.295+02:00</td>\n",
       "      <td>134</td>\n",
       "      <td>14</td>\n",
       "      <td>Monday</td>\n",
       "      <td>19.438889</td>\n",
       "      <td>13</td>\n",
       "      <td>Aniko</td>\n",
       "      <td>Utazas</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1526318804848</td>\n",
       "      <td>7200000</td>\n",
       "      <td>2018-05-14T19:26:44.848+02:00</td>\n",
       "      <td>134</td>\n",
       "      <td>14</td>\n",
       "      <td>Monday</td>\n",
       "      <td>19.445556</td>\n",
       "      <td>14</td>\n",
       "      <td>Erkezes/Indulas</td>\n",
       "      <td>Dési Out</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2691</th>\n",
       "      <td>1582145536113</td>\n",
       "      <td>3600000</td>\n",
       "      <td>2020-02-19T21:52:16.113+01:00</td>\n",
       "      <td>50</td>\n",
       "      <td>19</td>\n",
       "      <td>Wednesday</td>\n",
       "      <td>21.871111</td>\n",
       "      <td>3144</td>\n",
       "      <td>Erik</td>\n",
       "      <td>Gamma</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2692</th>\n",
       "      <td>1582145666519</td>\n",
       "      <td>3600000</td>\n",
       "      <td>2020-02-19T21:54:26.519+01:00</td>\n",
       "      <td>50</td>\n",
       "      <td>19</td>\n",
       "      <td>Wednesday</td>\n",
       "      <td>21.907222</td>\n",
       "      <td>3145</td>\n",
       "      <td>Aniko</td>\n",
       "      <td>Utazas</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2693</th>\n",
       "      <td>1582219463357</td>\n",
       "      <td>3600000</td>\n",
       "      <td>2020-02-20T18:24:23.357+01:00</td>\n",
       "      <td>51</td>\n",
       "      <td>20</td>\n",
       "      <td>Thursday</td>\n",
       "      <td>18.406389</td>\n",
       "      <td>3146</td>\n",
       "      <td>Erik</td>\n",
       "      <td>Prog</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2694</th>\n",
       "      <td>1582223593459</td>\n",
       "      <td>3600000</td>\n",
       "      <td>2020-02-20T19:33:13.459+01:00</td>\n",
       "      <td>51</td>\n",
       "      <td>20</td>\n",
       "      <td>Thursday</td>\n",
       "      <td>19.553611</td>\n",
       "      <td>3147</td>\n",
       "      <td>Erik</td>\n",
       "      <td>Planning</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2695</th>\n",
       "      <td>1582277491877</td>\n",
       "      <td>3600000</td>\n",
       "      <td>2020-02-21T10:31:31.877+01:00</td>\n",
       "      <td>52</td>\n",
       "      <td>21</td>\n",
       "      <td>Friday</td>\n",
       "      <td>10.525278</td>\n",
       "      <td>3148</td>\n",
       "      <td>Erik</td>\n",
       "      <td>Gamma</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2696 rows × 10 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "       Milliseconds  timezoneOffset                      timestamp  DayOfYear  \\\n",
       "0     1230751126776         3600000  2008-12-31T20:18:46.776+01:00        366   \n",
       "1     1526304739951         7200000  2018-05-14T15:32:19.951+02:00        134   \n",
       "2     1526306116707         7200000  2018-05-14T15:55:16.707+02:00        134   \n",
       "3     1526318780295         7200000  2018-05-14T19:26:20.295+02:00        134   \n",
       "4     1526318804848         7200000  2018-05-14T19:26:44.848+02:00        134   \n",
       "...             ...             ...                            ...        ...   \n",
       "2691  1582145536113         3600000  2020-02-19T21:52:16.113+01:00         50   \n",
       "2692  1582145666519         3600000  2020-02-19T21:54:26.519+01:00         50   \n",
       "2693  1582219463357         3600000  2020-02-20T18:24:23.357+01:00         51   \n",
       "2694  1582223593459         3600000  2020-02-20T19:33:13.459+01:00         51   \n",
       "2695  1582277491877         3600000  2020-02-21T10:31:31.877+01:00         52   \n",
       "\n",
       "      DayOfMonth  DayOfWeek  TimeOfDay   _id             cat1      cat2  \n",
       "0             31  Wednesday  20.312778  2903         Toltesek    PSVita  \n",
       "1             14     Monday  15.538611    10  Erkezes/Indulas  Dési Out  \n",
       "2             14     Monday  15.921111    11  Erkezes/Indulas   Dési In  \n",
       "3             14     Monday  19.438889    13            Aniko    Utazas  \n",
       "4             14     Monday  19.445556    14  Erkezes/Indulas  Dési Out  \n",
       "...          ...        ...        ...   ...              ...       ...  \n",
       "2691          19  Wednesday  21.871111  3144             Erik     Gamma  \n",
       "2692          19  Wednesday  21.907222  3145            Aniko    Utazas  \n",
       "2693          20   Thursday  18.406389  3146             Erik      Prog  \n",
       "2694          20   Thursday  19.553611  3147             Erik  Planning  \n",
       "2695          21     Friday  10.525278  3148             Erik     Gamma  \n",
       "\n",
       "[2696 rows x 10 columns]"
      ]
     },
     "execution_count": 82,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import dtale\n",
    "\n",
    "# survey_public_link = 'C:/Users/asusu/Documents/REPO/data/survey_results_public.csv'\n",
    "# survey_schema_link = 'C:/Users/asusu/Documents/REPO/data/survey_results_schema.csv'\n",
    "\n",
    "tap_Log_link= 'C:/Users/Erik_Dubrovszkij/Documents/Projects/Homee/Tap_Log_Export_20200221.csv'\n",
    "\n",
    "df = pd.read_csv(tap_Log_link)\n",
    "remove_nan_colm_data = df.dropna(axis='columns', how='all')\n",
    "remove_nan_colm_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 83,
   "metadata": {},
   "outputs": [],
   "source": [
    "remove_nan_colm_data.drop(remove_nan_colm_data.columns[[0,1]],axis=1,inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Beszelgetes    199\n",
       "Aktus          157\n",
       "VideoA         133\n",
       "Utazas         120\n",
       "Vita            57\n",
       "JatekA          53\n",
       "Kivanos         52\n",
       "Name: cat2, dtype: int64"
      ]
     },
     "execution_count": 85,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "name = ['Aniko']\n",
    "filtAniko = remove_nan_colm_data['cat1'].isin(name)\n",
    "df_Aniko = remove_nan_colm_data.loc[filtAniko]\n",
    "df_Aniko['cat2'].value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"350\"\n",
       "            src=\"http://EPHUBUDW0340:40000/dtale/iframe/8\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x17a1e3136a0>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": []
     },
     "execution_count": 86,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /charts/_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n",
      "Exception on /charts/_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-02-27 16:39:37,332 - ERROR    - Exception on /charts/_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n",
      "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-02-27 16:39:37,336 - ERROR    - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /charts/_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n",
      "Exception on /charts/_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-02-27 16:40:28,561 - ERROR    - Exception on /charts/_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n",
      "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-02-27 16:40:28,565 - ERROR    - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\flask\\app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1459, in dispatch\n",
      "    response.set_data(self.callback_map[output][\"callback\"](*args))\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dash\\dash.py\", line 1339, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"c:\\program files\\python37\\lib\\site-packages\\dtale\\dash_application\\views.py\", line 328, in display_page\n",
      "    df = DATA[get_data_id(pathname)]\n",
      "KeyError: '8'\n"
     ]
    }
   ],
   "source": [
    "d = dtale.show(df_Aniko)\n",
    "d"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
